# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict

- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]

    - id: ruff
      name: ruff
      entry: ruff check
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      require_serial: true
