name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run tests
        run: nix develop --command pytest

      - name: Type checking
        run: nix develop --command mypy .

      - name: Lint
        run: |
          nix develop --command black --check .
          nix develop --command ruff check .
